version: "3.8"
services:
  db:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: futureskill
    restart: always
  web:
    build: ./web
    environment:
      MYSQL_DATABASE: futureskill
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      MYSQL_HOST: db
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: on-failure